# Generated by Django 4.2.6 on 2023-10-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_malumot_about_malumot_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='malumot',
            name='image',
            field=models.ImageField(default=1, upload_to='media/user_info/'),
            preserve_default=False,
        ),
    ]
