# Generated by Django 4.2.6 on 2023-10-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_malumot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malumot',
            name='image',
            field=models.ImageField(upload_to='user_info/'),
        ),
    ]
